services:
  rustdesk-api:
    image: lejianwen/rustdesk-api
    container_name: rustdesk-api
    ports:
      - 21114:21114
    volumes:
      - /data/rustdesk/api:/app/data #将数据库挂载出来方便备份
    restart: unless-stopped